version: '2'

services:
  http-proxy:
    container_name: http-proxy
    build: ./
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
      - "19322:19322/udp"
    environment:
      CONTAINER_NAME: http-proxy